### ISSUE TITLE
Clicking above or below modal doesn't close modal

### ISSUE THREAD

**Issue by JasonMFry** [rundis/elm-bootstrap#109]
In case it's relevant I'm using the latest Safari browser, but this issue also occurs with Chrome.

It seems the modal element has padding or something above and below the part of the element that is displayed, but I couldn't figure out what's _really_ happening. See screenshot. If you click in the blue shaded area the modal won't close, but if you click in the orange shaded area it will close.

(elm-bootstrap is great, btw! Thanks for your hard work!!)

![screen shot 2018-06-11 at 11 16 48 am 2](https://user-images.githubusercontent.com/166681/41240810-5f6881a0-6d69-11e8-90c1-24b8af8e301b.png)

**Comment by rundis** [comment]
Fixed by https://github.com/rundis/elm-bootstrap/commit/72bfbcc1ab1c3444ce06e80b83ca3e7ecad23130
