### ISSUE TITLE
Navbar is always collapsed

### ISSUE THREAD

**Issue by TeodoroFilippini** [rundis/elm-bootstrap#113]
Contrary to what is stated on the [relative Elm-bootstrap page](http://elm-bootstrap.info/navbar), the Navbar is always collapsed into mobile view. This seems to be [an issue with the `navbar-toggler` class](https://stackoverflow.com/questions/45676291/bootstrap-4-toggleable-navbar) in Bootstrap 4 beta, and replacing it with `navbar-expand` fixes the issue. Hence, that should probably be done within the library.

**Comment by rundis** [comment]
>Contrary to what is stated on the relative Elm-bootstrap page
The elm-bootstrap.info site is made with elm-bootstrap. The example navbars behave as expected/stated there don't they ?

The latest version of elm-bootstrap requires the bootstrap 4 release css. And it does use the -expand classes.

**Comment by TeodoroFilippini** [comment]
Hello @rundis 

Thanks for your quick response. Indeed downgrading to the 4.0.0 release css fixed the behavior. Thanks a lot.
