### ISSUE TITLE
Accordion.toggle misbehaves if passed anything other than text

### ISSUE THREAD

**Issue by JasonMFry** [rundis/elm-bootstrap#115]
If we pass text to `Accordion.toggle` then it collapses and expands as expected. If we pass an img or span (and presumably anything else) then it does not collapse or expand, but instead sends a `OnLocationChange` msg (which is the msg type we pass to `Navigation.programWithFlags`).

works: 
`Accordion.toggle [ ] [ text "Name and Description"]`

doesn't work: 
`Accordion.toggle [ ] [ img ([ src ("chevron-right.svg"), alt "Collapse Content" ]) [] ]`

clicking text works, clicking img doesn't work: 
`Accordion.toggle [ ] [ text "Name and Description", img ([ src ("chevron-right.svg"), alt "Collapse Content" ]) [] ]`

**Comment by JasonMFry** [comment]
I'd love to hunt this down and fix it, but don't have a whole of time :( If you have a guess about what's causing this and can point me in the right direction so I don't have to spend a lot of time figuring our _where_ the issue is, I'll do my best.

**Comment by dseebacher** [comment]
This is a nice one...
The code uses `DOM.target` (might be some child node within the header link) but it should rather use `DOM.currentTarget`. Unfortunately there is no such function in `debois/elm-dom`.

Here some missing code:
```elm
import Json.Decode as Decode exposing (field, Decoder)

currentTarget : Decoder a -> Decoder a
currentTarget decoder =
    field "currentTarget" decoder
```

And the modified function in `Accodion.elm`:
```elm
heightDecoder : Json.Decoder Float
heightDecoder =
    currentTarget <|
        DOM.parentElement <|
            DOM.nextSibling <|
                DOM.childNode 0 <|
                    DOM.offsetHeight
```

That said, I'm not sure if the whole DOM traversing approach is a good idea, but I don't have enough insight so I will let you decide ;)

**Comment by JasonMFry** [comment]
@dseebacher this works like a charm for us, thanks!
