### ISSUE TITLE
Change upper version for debois/elm-dom in elm-package.json to 1.3.0

### ISSUE THREAD

**Issue by sohaibiftikhar** [rundis/elm-bootstrap#128]
Currently the package `debois/elm-dom` uses `"1.0.0 <= v < 2.0.0"` as version limits. This should be changed to `"1.0.0 <= v < 1.3.0"`. As `debois/elm-dom 1.3.0` bumps to `elm-19` which breaks the package install.

**Comment by rundis** [comment]
No longer using elm-dom.
