### ISSUE TITLE
Accordion does not have the "accordion" class around the parent div, so cards appear detached from each other.

### ISSUE THREAD

**Issue by andrewjackman** [rundis/elm-bootstrap#129]
If you look carefully at the bootstrap examples, and accordion has CSS that styles the set of cards, making them appear as a single element with correct rounding of the first and last card top and bottom borders, all other cards having square borders.

https://getbootstrap.com/docs/4.1/components/collapse/

This works because the div containing the cards has the class "accordion". 

This "accordion" class is missing in the elm-bootstrap Accordion, and the cards appear detached from each other and all have rounded corners.

**Comment by rundis** [comment]
This has been fixed on master now. (class was added in one of the point releases of TWBS 4
