### ISSUE TITLE
Add possibility to add attributes to form groups

### ISSUE THREAD

**Issue by Munksgaard** [rundis/elm-bootstrap#136]
Currently Form.Group takes a list of Form.Option as the first argument, but as far as I can tell, there's no way to actually create a Form.Option value. It would be nice to have something similar to the Form.Input.attrs function in order to attach arbitrary attributes to a form group.

**Comment by rundis** [comment]
Lol. The option for attrs is there, however no function to create it is exposed. Feel free to add a pr with a `attrs` or `groupAttrs` function, otherwise I'll get to it when I find time to batch up for a new version.
