### ISSUE TITLE
Is striped for tables working?

### ISSUE THREAD

**Issue by mattiasw2** [rundis/elm-bootstrap#138]
When clicking in the checkbox at

http://elm-bootstrap.info/table

I see no difference.

**Comment by frandibar** [comment]
works for me.

**Comment by mattiasw2** [comment]
![image](https://user-images.githubusercontent.com/1294931/48968842-9a53a880-eff5-11e8-87da-bfdbcbe4c5e0.png)

You are correct the stripes are there, but not visible. If I also select inverse, then are visible. So I need to change the colors used.

![image](https://user-images.githubusercontent.com/1294931/48968885-00d8c680-eff6-11e8-80f3-b4f8c3e32d3a.png)
