### ISSUE TITLE
Possible to tune in card column count

### ISSUE THREAD

**Issue by milogert** [rundis/elm-bootstrap#144]
Just started using this, and I think it's great!

One thing I have run into though is a seemingly missing way to customize the number of columns in the card column. Essentially they are stuck at 1 column for `xs` and `sm` and then 3 columns for `md` and up.

For my use case my cards have a bit of data in them and they can be of variable size. I would like to customize the column count for `md` and up to be 2 rather than 3 (maybe 3 at `xl` but that's another step).

Is this possible? It looks like you need to customize the `column-count` attribute but I don't see a way to do it within this library.

**Comment by rundis** [comment]
I think you'd need to tinker with theming your own bootstrap css to achieve that.
