### ISSUE TITLE
bootstrap tab not working  

### ISSUE THREAD

**Issue by theepankonesh** [rundis/elm-bootstrap#147]
<!doctype html>
<html lang="en">

<head>
  <title>Hello, world!</title>
  
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">

  
  <link href="assets/css/material-dashboard.css" rel="stylesheet" />
  <link href="assets/css/jasny-bootstrap.min.css" rel="stylesheet" />
  

  

</head>

<body>
  <div class="wrapper ">
    <div class="sidebar" data-color="purple" data-background-color="white">
      
      <div class="logo">
        <a  class="navbar-brand">
          <img src="logo2.png" style="width: 275px">
        </a>
      </div>
      <div class="sidebar-wrapper">
        <ul class="nav">
          <li class="nav-item">
            <a class="nav-link" href="./index.html">
              <i class="material-icons">dashboard</i>
              <p>Dashboard</p>
            </a>
          </li>
          
          <li class="nav-item active ">
            <a class="nav-link" href="./add_user.html">
              <i class="material-icons">person_add</i>
              <p>Add New User</p>
            </a>
          </li>

          <li class="nav-item ">
            <a class="nav-link" href="./user_profile.html">
              <i class="material-icons">person</i>
              <p>User Profile</p>
            </a>
          </li>

        </ul>
      </div>
    </div>
    <div class="main-panel">
      
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end">
            <ul class="navbar-nav">
              <li class="nav-item">
                
              </li>
              
            </ul>
          </div>
        </div>
      </nav>
      
      <div class="content">
        <div class="container-fluid  ">
          <div class="row">
            <div class="col-md-8">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title">Personal Information</h4> 
                </div>
                <div class="card-body">
                  <div class="card-body">
                  <form>

                    <div class="row">
                      <div class="row">
                      <div class="col-md-6">
                        <div class="fileinput fileinput-new text-center" data-provides="fileinput">
                           <div class="fileinput-new thumbnail img-raised" style="width: 200px; height: 200px">
                          <img src="https://epicattorneymarketing.com/wp-content/uploads/2016/07/Headshot-Placeholder-1.png" alt="..." width="200px" height="200px" >
                           </div>
                           <div class="fileinput-preview fileinput-exists thumbnail img-raised " style="width: 200px; height: 200px;"></div>
                           <div>
                          <span class="btn btn-raised btn-round btn-primary btn-file" style="width: 200px; padding-right: -50px;">
                             <span class="fileinput-new">Select image</span>
                             <span class="fileinput-exists">Change</span>
                             <input type="file" name="..." />
                          </span>
                           </div>
                        </div>
                      </div>
                    </div>

                      <div class="col-md-4 contentcontainer med left" style="margin-left: 2px; margin-top:30px  ">
                        <div class="form-group">
                          <input type="text" class="form-control" placeholder="First Name" required="" name="f_name">
                        </div>
                      </div>
                      
                    <div class="col-md-5 contentcontainer med left" style="margin-left: 555px; margin-top: -235px">
                        <div class="form-group">
                          <input type="text" class="form-control" placeholder="Last Name" required="" name="l_name">
                        </div>
                      </div>

                      <div  class="col-md-3 contentcontainer med left" style="margin-left: 202px; margin-top: -170px">
                        <div class="form-group ">
                          <select class="form-control selectpicker" data-style="btn btn-link" id="exampleFormControlSelect1" name="gender">
                          <option disabled selected valu > Gender</option>
                           <option>Male</option>
                            <option>Female</option>
                          </select>
                           </div>
                        </div>

                      <div class="col-md-3 contentcontainer med left" style="margin-left: 5px; margin-top: -165px">
                        <div class="form-group">
                          <input type="text" class="form-control" placeholder="Place of Birth" name="placeofb">
                        </div>
                      </div>

                      <div class="col-md-3 contentcontainer med left" style="margin-left: 720px;margin-top: -165px ">
                        <div class="form-group">
                          <input placeholder="Date of Birth" class="form-control" type="text" onfocus="(this.type='date')" onblur="(this.type='text')" id="date" required="" name="DOB">
                        </div>
                      </div>

                      <div class="col-md-9 contentcontainer med left" style="margin-left: 205px; margin-top: -100px ">
                        <div class="form-group">
                          <input type="email" class="form-control" placeholder="Email Address" name="email">
                        </div>
                      </div>

                      <div class="col-md-2 contentcontainer med left" style="margin-left: 800px; margin-top:-280px  ">
                        <div class="form-group">
                          <input type="text" class="form-control" placeholder="ID" name="id">
                        </div>
                      </div>
                      </div>

                   
                        <div class="card">
                           
                          <nav>
                            <div class="nav nav-tabs" id="nav-tab" role="tablist">
                              <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#myTab" role="tab" aria-controls="nav-home" aria-selected="true">Address</a>
                              <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Address 2</a>
                              <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="false">Address 3</a>
                              <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="false">Address 4</a>
                              <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="false">Address 5</a>
                            </div>
                          </nav>
                          <div class="tab-content" id="nav-tabContent">
                            <div class="tab-pane fade show active" id="myTab" role="tabpanel" aria-labelledby="nav-home-tab"></div>
                            <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">fgfgfgfgfgfdghhdh</div>
                            <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab"></div>
                          </div>

                         </div>   
                            
                            

                        

      

                

                    <button type="submit" class="btn btn-primary pull-right">Save Profile</button>
                    <div class="clearfix"></div>

                    </div>
                    </form>
             

      <div class="content">
        <div class="container-fluid">
          
        </div>
      </div>
      
    </div>
  </div>
       
  <script src="assets/js/material-dashboard.js"> </script>
  <script src="assets/js/jquery-3.3.1.min.js"></script>
  <script src="assets/js/jasny-bootstrap.min.js"></script>
  <script src="../assets/js/core/bootstrap-material-design.min.js"></script>

<script>

$('#myTab a').on('click', function (e) {
  e.preventDefault()
  $(this).tab('show')
})
 

</script>
 
</body>
</html>

**Comment by rundis** [comment]
I fail to see how this has anything todo with **elm**-bootstrap.
