### ISSUE TITLE
Add ability to create Input with type submit

### ISSUE THREAD

**Issue by bryce13950** [rundis/elm-bootstrap#149]
As is, I cannot see a way to create an input element with type of submit. This makes it a bit difficult to use built in browser validation attributes. I would think that it would make sense to add this to the current Button module, and if this sounds like a good idea to you then I would be happy to do it.

**Comment by rundis** [comment]
You could use `Button.attrs` for the type (`type_` in Elm html) attribute ?

**Comment by bryce13950** [comment]
Is there a reason not to add it to the Button module?

**Comment by rundis** [comment]
Well the module has checkboxButton, radioButton and linkButton, so adding an option for type_ would invite potentially more confusion/possibility of unexpected behaviour. Another option would be to to have a submitButton function and resetButton function added to the module. That might be the best solution given the current api. Not sure how to handle a onSubmit shorthand/option though as that would only make sense for a submitButton I suppose ?
