### ISSUE TITLE
Draggable Carousel

### ISSUE THREAD

**Issue by TomasBarry** [rundis/elm-bootstrap#150]
Is there functionality to allow for a responsive carousel? I haven't been able to see anywhere that indicates that this is supported.

Are the draggable carousels [like here](http://kenwheeler.github.io/slick/) possible?

**Comment by rundis** [comment]
Mostly targeting to support whats here: https://getbootstrap.com/docs/4.3/components/carousel/
No plans to add draggable support tbh
