### ISSUE TITLE
Dropdown cannot be opened again once closed in Chrome

### ISSUE THREAD

**Issue by lucdoebereiner** [rundis/elm-bootstrap#161]
Once opened and closed a dropdown cannot be opened again in Chrome (tested with Version 75.0.3770.80) (see all the examples on  http://elm-bootstrap.info/dropdown). After the close, the items only appear when one scrolls or uses the up/down keys.

On Firefox it works fine.

**Comment by rundis** [comment]
Doh! I wonder what changed from 74.x to 75.x that caused this. Currently I haven't got a clue.

**Comment by ljnicol** [comment]
We're also having this issue. It could be something to do with triggering a DOM update?

**Comment by FrancoAra** [comment]
Having the same issue :(
