### ISSUE TITLE
Form.Range is not exposed in elm.json file

### ISSUE THREAD

**Issue by tymoshen** [rundis/elm-bootstrap#169]
Hi, 

It seems that Form.Range module is not exposed in elm.json file. Additionally, there is an error in range component usage example (in comments):
`Radio.onInput MyRangeMsg -> Range.onInput MyRangeMsg `

**Comment by tymoshen** [comment]
Tnx for merging it in. I've found another typo in the comments (line 31) and maybe someone else will fix it in another PR. Maybe it will be me :)

**Comment by acyuta108** [comment]
I have 5.2.0 installed (default installed by elm) but it does not expose Range. When will it be available in the default release?

BTW, thanks for your amazing work!
