### ISSUE TITLE
Expose a way to know which tab is active

### ISSUE THREAD

**Issue by passiomatic** [rundis/elm-bootstrap#186]
Thank you for this great package! I'm opening this to suggest a way to know which `Tab` is active. 

At the moment I've solved the issue  by copying the relevant `Tab.elm` code in my project and adding a new function: see https://github.com/passiomatic/elm-designer/blob/master/src/Bootstrap/Tab.elm#L94  

Such function exposes the internal `State. activeTab_`  so the caller can figure out what to do if a tab is hidden or shown. In my use-case generating a Tab content is quite expensive so it is better to avoid to run its view completely if it isn't really needed. 

Not sure if this is the best way to proceed but as a general rule this could be applied to other similar widgets as well. For example  I'm noticing now that Accordion has `isOpen` function which works with a similar purpose .

**Comment by acyuta108** [comment]
Are you not keeping state of tabState in the model?
Based on the instructions, I placed tabState in the model and I init as Tab.initialState. You can check the Msg when the user clicks on a tab: 
```json
TabMsg State …
▾0 = {
activeTab = Just "tabItem2"
visibility = Showing
}
```

**Comment by passiomatic** [comment]
"Are you not keeping state of tabState in the model?"

Yes, I am. But can I access `State` record on the case/of? In the Elm Bootstrap package the custom type is private.

**Comment by rundis** [comment]
one workaround might be to use the Browser.navigation module, the chosen tab could be sent as a url hash (nice for deep linking as well). Then you can pick up the active tab and just in time render the view (and fetch needed data, probably with your own custom state handling for pending/success/error states for the remote request(s) etc).

**Comment by acyuta108** [comment]
Indeed, this is a [opaque type](https://sporto.github.io/elm-patterns/advanced/opaque-types.html) (https://github.com/rundis/elm-bootstrap/blob/master/src/Bootstrap/Tab.elm#L84)
So unfortunately I don't know how one can access these values (I'm somewhat new to Elm). From what I can tell this pattern is meant, as you say, to be private in order to not break apps with future changes, which in this instance kind of sucks if you ask me since it seems like it would be a very useful thing and would support the most basic and standard Elm pattern ``` listen to Msg in update -> update model -> (optional) trigger Cmd ```.

Of course @rundis knows best (he's the author after all). His workaround should work and it's probably a more generic and robust way to do it, backwards compatible that won't break if any internal changes occur. Thanks for the learning experience, I hope this also helps others. 
([This is as far as I got doing the case...of approach](https://ellie-app.com/f5RHXYsy5yYa1))

**Comment by passiomatic** [comment]
On my side I've solved the issue by copying and edit the original code like I've written in the first message so it is OK if things stay the way they are. 

My intent was to understand if there was a will to expose "current tab" information in a subsequent release.

**Comment by tankorsmash** [comment]
It's a bummer this was closed because I'm facing the same issue, where I'd like to fire a Cmd when changing to a specific tab, and since `Tab.State` is opaque, there isn't a way to query the activeState inside it.

**Comment by KovaxG** [comment]
I also run into this issue (still using this in 2026, yay) but I managed to find a nicer workaround if anyone is interested:

I am capturing the button click on the items, and sending my own message. In the update function, I am also updating the tab state with Tab.customInitialState. I noticed that the message sent in the config is not sent anymore if you add `onClick` handlers to the items.
```elm
-- view 
Tab.config TabMsg -- this will be ignored
  |> Tab.withAnimation
  |> Tab.items
    [ Tab.item
      { id = "First"
      , link = Tab.link [onClick (SetTab "First")] [text "First Tab"]
      , pane = Tab.pane [] []
      }
    , Tab.item
      { id = "Second"
      , link = Tab.link [onClick (SetTab "Second")] [text "Second Tab"]
      , pane = Tab.pane [] []
      }
    ]
  |> Tab.view state.tabState
```

And in the handler:

```elm
-- update
SetTab str -> ( { model | tabId = str, tabState = Tab.customInitialState str}, Cmd.none)
```

This works for me, but is a bit goofy. At least I don't have to duplicate the code, but I do wish something like this existed in the Tab module:

```elm
activeTab : State -> Maybe String
activeTab (State s) = s.activeTab
```
Maybe if anyone forks this project this is something to consider.
