### ISSUE TITLE
Modals Without Close Buttons

### ISSUE THREAD

**Issue by eliaslfox** [rundis/elm-bootstrap#25]
It would be nice to have the capability to display a modal without an explicit close button. The modal could then be closed by some other use interaction, such as clicking a submit button. If this sounds useful, I could make a pr.

**Comment by rundis** [comment]
I guess you mean having a modal with a header without the close "x" which is automatically added if you include a header right ? 

The module already includes a `hiddenState` function which you can use to ensure the modal closes, say from a custom message (whether it be a submit or custom close button).

What I'm getting at is, do you explicitly need the user to not be able to close the modal with the right hand corner`X` button (when you have a header) ? Just trying to understand your use case better.

And to ensure you don't waste your time, an example of what you envisage would be really useful before submitting a PR (ie what would the api look like).

cheers
-magnus

**Comment by eliaslfox** [comment]
Having a custom header solves my problem. I didn't realize it would take the place of the close button. Thank you

**Comment by rundis** [comment]
Seems to be resolved ?
