### ISSUE TITLE
Passing down attrs to Dropdown component 

### ISSUE THREAD

**Issue by holandes22** [rundis/elm-bootstrap#31]
I'm trying to make a Dropdown scrollable. I though of using the following CSS

```
.scrollable-menu {
  height: auto;
  max-height: 150px;
  overflow-x: hidden;
}
```

but I don't see any place where I would be able to pass down this class attr to Dropdown.dropdown.
I checked the relevant [source code](https://github.com/rundis/elm-bootstrap/blob/master/src/Bootstrap/Dropdown.elm#L249) and seems that it does not allow to inject arbitrary classes to the div. Is there any way to do this that I'm missing?

Just to clarify, I know that this specific issue can be solved by targeting the parent div and applying the css to the dropdown-menu item, but just interested to know if there is way to pass down arbitrary attrs.

This is an awesome library, thank you so much for this!

**Comment by rundis** [comment]
Tx for the report. I´ll add support for this to the next release.

**Comment by holandes22** [comment]
Having an API similar to the HTML attrs would be great. Thank you!

**Comment by rundis** [comment]
Fixed on master
