### ISSUE TITLE
Bootstrap.Form.Select.select: does select have onInput event ?

### ISSUE THREAD

**Issue by clouddie** [rundis/elm-bootstrap#56]
Hi,

Even with correcting the example as per issue https://github.com/rundis/elm-bootstrap/issues/54, I cannot get the select to emit an event on user Input.

Are you sure Select emits a ```onInput``` Html event, isn't it an ```onChange``` ?

**Comment by folkertdev** [comment]
This thread from the [elm html package](https://github.com/elm-lang/html/issues/71) says 'onchange' is considered the correct function to use. You can make a pull-request if you want.

**Comment by clouddie** [comment]
@folkertdev Thanks, here is the pull request : https://github.com/rundis/elm-bootstrap/pull/57

**Comment by rundis** [comment]
Hm.. tested both in Firefox, Chrome and Safari : https://ellie-app.com/3gn3Kt6XFK8a1/0

But then again I found this issue, which I suppose recommends onChange
https://bugzilla.mozilla.org/show_bug.cgi?id=312094
