### ISSUE TITLE
Cannot find module 'Bootstrap.Form.Fieldset'

### ISSUE THREAD

**Issue by herdibintang** [rundis/elm-bootstrap#58]
Hello.
https://runelm.io/c/8er is the example.

**Comment by folkertdev** [comment]
The Fieldset module is not exposed in the currently published version (2.0.0), but will be in the next release

**Comment by herdibintang** [comment]
I'm very sorry. What i mean is 'Bootstrap.Form.Fieldset'. Is the answer still the same?

**Comment by folkertdev** [comment]
yes

**Comment by herdibintang** [comment]
Thanks
