### ISSUE TITLE
Be informed of tab change to facilitate navigation/routing

### ISSUE THREAD

**Issue by ahri** [rundis/elm-bootstrap#59]
Being informed of tab changes would allow me to update the hash of my SPA allowing deep-linking into a tab control: https://ellie-app.com/3h8n9K8tXhva1/1 is an example use-case that currently doesn't work, but illustrates the desired behaviour.

**Comment by ahri** [comment]
I'll upgrade to 3.0.0 soon and come back to this; perhaps there's no real need for it after all.

**Comment by andre-dietrich** [comment]
Hi, first of all great work ...
I have also a question concerning the tab-navigation ... would it be possible to add a function like the following 
```elm
getActiveTab : State -> Maybe String
getActiveTab (State state) =
  state.activeTab
```
To your Tab.elm module? It would ease a lot for me, no need of URL parsing ... etc. ... Or do you have another suggestion of an handy way to get the id of the active tab? 

Thanks a lot ...

**Comment by rundis** [comment]
@andre-dietrich It would be easy, but I'd love to see a use case that merits it (or a hopefully something better). In what circumstance would you "poll" for the id of the active tab and what would you use that information for ?

**Comment by ahri** [comment]
Just a note; I'm not at all sure that I want anything out of this. I haven't yet upgraded to v3 and it's not high on my priority list at the moment.

Default href behaviour seems to be a much better approach for my SPA :)

**Comment by miniBill** [comment]
@rundis beside deep linking, having a getter or a msg that informs about the current tab can help with saving/restoring state for webapps that want to feel native

**Comment by rundis** [comment]
Closing this. Open to design suggestions.
