### ISSUE TITLE
Custom attributes

### ISSUE THREAD

**Issue by splodingsocks** [rundis/elm-bootstrap#61]
@rundis I just took my first serious stab at using this today, and it's fantastic. I'm loving it. Big kudos to you for putting in the time and effort here. Thank you so much.

One need I'm running into that's not covered is to add custom classes, or custom styles to a bootstrap button. I took a quick look at the API and didn't see a way to do that at the moment. Do you think it'd be a good idea to provide an "escape hatch" of sorts, for when a user wants to apply some general HTML attribute to a button? Something like `Bootstrap.Button.attribute : Html.Attribute -> Bootstrap.Button.Option`?

That might be a good general pattern to follow through the rest of the library, though it gets tricky when there isn't an obvious DOM element to which the attributes would be applied.

Anyway, what are your thoughts on this?

**Comment by rundis** [comment]
Cheers !

Wouldn´t this function do the trick : http://package.elm-lang.org/packages/rundis/elm-bootstrap/3.0.0/Bootstrap-Button#attrs  ?
(In hindsight the abbrevieation might not have been ideal for discoverability 😞 )

It't sort of a consistent theme that most modules have one or more of these escape hatches (depending on whether the module encapsulates just a flat element or something composed of multiple elements).

**Comment by splodingsocks** [comment]
Well don't I feel silly. That's exactly what I was looking for, and the abbreviation is fine, IMO. I must've just overlooked it. Thank you!

**Comment by rundis** [comment]
No worries !

Oh and thx a bunch for elmtown, love it ❤️

**Comment by splodingsocks** [comment]
You are more than welcome!
