### ISSUE TITLE
http://elm-bootstrap.info/getting-started uses 100% of the CPU on Safari/OS X

### ISSUE THREAD

**Issue by mariosangiorgio** [rundis/elm-bootstrap#62]
I haven't been able to track down what's causing it, but on my Mac every time I open http://elm-bootstrap.info/getting-started Safari uses 100% of the CPU as soon as I scroll down a bit.

The same page works fine with Chrome on the same laptop.

If it isn't something obvious in the next days I can try and see what's going on using the developer tools.

**Comment by rundis** [comment]
tx for the report. I'll look into it after my holidays !

**Comment by rundis** [comment]
I was initially able to reproduce this initially, but no longer on my to mac's. Is this stil a problem for you ?

**Comment by mariosangiorgio** [comment]
Everything works fine for me as well. Thanks for having looked into it!
