### ISSUE TITLE
Is it possible for the Accordion to only show one card at a time

### ISSUE THREAD

**Issue by 7er** [rundis/elm-bootstrap#66]
I just tried the Accordion and it seems to work fine. I would have liked to be able to specify that only one card should be shown at a time, like this : https://v4-alpha.getbootstrap.com/components/collapse/#accordion-example, but it doesn't seem to be supported.

After skimming the code it seems that changing Accordion.mapCardState or a similar function could be used to not only toggle the visibility of the clicked card but also set the visibility of all other cards in the accordion to Hidden.

Another question:
I am using several accordions in my application (one per page). I am guessing that this should work out fine as long as I use a unique Msg value constructor and accordionState in Model for each accordion, right?

**Comment by rundis** [comment]
1. I did try to implement support for that, but couldn't get the animations to line up properly. I might revisit this later if/when I get the time, but don't hold your breath. If it's important to you by all means feel free to have a crack at a PR !
(imho the support for more tricky DOM related stuff in Elm is proving somewhat limiting for cases like this, or at least my ability to figure out workarounds is starting to reach it's limits...)

2. It should be fine to have multiples of any of the "components" in elm-bootstrap. As you say they have their own state and messages, if you don't mix them you should be fine !

**Comment by Ephs05msm** [comment]
Hi, quick variation on this question: how can an accordion card's default visibility be set to "Shown"? mapCardState is not exposed, and I don't see an option to declare this.

Thanks for the help.
