### ISSUE TITLE
Modal module requires use of CDN.stylesheet

### ISSUE THREAD

**Issue by OwenOKI** [rundis/elm-bootstrap#67]
In making a simple test case, the Modal forms do not work for me (in I.E. 11 nor chrome) if I do not include a usage of CDN.stylesheet somewhere in my view.  To demonstrate, I have created a very basic Modal form from a trimmed down BootstrapLayout example.

The difference between the working and failing .elm files is simply the following:

```
C:>diff minWorks.elm minFails.elm
66,67c66
<     [ CDN.stylesheet
<     , h2 [] [ text "Getting started Works" ]
---
>     [ h2 [] [ text "Getting started Fails" ]

```
compiling minFails.elm and opening index.html in IE you will see something very similar to the image attached.  Doing the same with minWorks.elm (after your clear cache to make sure it rebuilds) works fine, and yeilds the attached pic...  (renamed .elm files to .txt for ease of upload)

Thanks for all your work, and until you get it fixed, I am happy to simply include a reference to CDN.stylesheet whenever I need to.

![minfails](https://user-images.githubusercontent.com/29714619/28642985-26544f54-7209-11e7-860c-d36c2c07453e.jpg)

![minworks](https://user-images.githubusercontent.com/29714619/28642986-2662af72-7209-11e7-898c-23eb850aa786.jpg)
[minFails.txt](https://github.com/rundis/elm-bootstrap/files/1178011/minFails.txt)
[minWorks.txt](https://github.com/rundis/elm-bootstrap/files/1178012/minWorks.txt)

**Comment by rundis** [comment]
You have to include the bootstrap stylesheet for most anything to work correctly.

As outlined in the documentation http://elm-bootstrap.info/getting-started you have 2 choices:
1. For simple apps use the Bootstrap.CDN convenience module. When using the stylesheet function as described it will create a html style node with the complete bootstrap css inlined
2. Alternatively and recommended for anything serious, you'll have a html file where you include the bootstrap stylesheet yourself explicitly and embed your elm application.
