### ISSUE TITLE
Carousel does not appear to work on IE11

### ISSUE THREAD

**Issue by OwenOKI** [rundis/elm-bootstrap#68]
Use IE11 (I know, but people still do it).

Visit the page http://elm-bootstrap.info/carousel

Compare the behavior there to the behavior you see on that page using Chrome.  For me, I was unable to get the slides to change.  The best I ever saw was that the slide changed once, but the original text was never cleared, so both text appeared.

I do not have a newer version of IE to test.
I am using Windows 7.

I implemented a sample Carousel with images and text, and buttons, which worked great on Chrome, but in IE11, failed.  I will not provide source since http://elm-bootstrap.info/carousel shows similar problems still.

Thanks.

**Comment by rundis** [comment]
Not going to put any effort into this. Sorry, but life's to short :)
