### ISSUE TITLE
Cannot find type `Bootstrap.Form.Option`. - `Bootstrap.Form` does not expose `Option`.

### ISSUE THREAD

**Issue by martinbryant** [rundis/elm-bootstrap#69]
So I am trying the following code for form validation but I get the above error message. 

checkValidationState field =
    case field.state of
        None ->
            ( Form.groupDanger, Input.danger, "" )

        Valid ->
            ( Form.groupSuccess, Input.success, "" )

        NotValid error ->
            ( Form.groupDanger, Input.danger, error )

The compiler infers the type as below, so when I add this line of code I get the error.

checkValidationState
    : { a | state : ValidationState }
    -> ( Bootstrap.Form.Option msg, Input.Option msg1, String )

Also a problem when trying to create a type for a ValidationType union type.

Can this be exposed?

**Comment by rundis** [comment]
It's exposed now. But then again the validation stuff got a whole lot less useful in the newly released 4.0.0 (twitter bootstrap threw things around to much to come up with anything nice in a timely manner with an upgrade taking priority).
