### ISSUE TITLE
Popover incompatible with v4-beta Popper.js styles

### ISSUE THREAD

**Issue by andrewhao** [rundis/elm-bootstrap#70]
I'm trying to integrate Elm-Bootstrap with a custom Bootstrap stylesheet generated from the latest v4-beta twbs. Tooltips seem to lack the styling they used to have - it does seem that the twbs project has transitioned from the Tether widget to the Popper widget.

I'm using the latest `3.0.0` release of elm-bootstrap.

<img width="298" alt="screen shot 2017-08-23 at 3 01 46 pm" src="https://user-images.githubusercontent.com/222583/29640630-a18d31f6-8814-11e7-9872-301111a7d0ee.png">

I can do some more investigation into this, but it seems like this project needs to update Popover CSS classes to reflect Popper styles: https://github.com/rundis/elm-bootstrap/blob/d6049e0461bf63cbc1005f83d78a7d4bc8bba1a8/src/Bootstrap/Popover.elm

https://github.com/twbs/bootstrap/compare/v4.0.0-alpha.6...v4-dev

**Comment by rundis** [comment]
Tx, 

Yeah I'm working on updating the lib to support the beta recently released. Bootstrap css changed quite a bit from alpha6 to beta.  

So recommendation for now:
elm-bootstrap 3.0 -> Use https://v4-alpha.getbootstrap.com/getting-started/download/
elm-bootstrap 4.0 (when ready) -> use https://getbootstrap.com/
