### ISSUE TITLE
Exposing Bootstrap.Form.Option

### ISSUE THREAD

**Issue by slashmili** [rundis/elm-bootstrap#73]
Hey!

What do you think about exposing `Bootstrap.Form.Option` ?

I want to write a helper function for my forms to return the group option..

```elm
-- pseudocode 
groupOption -> field -> List(Error) -> List (Form.Option msg) :
groupOption field errors =
  if field in errors
    BForm.groupDanger
  else
    []
view =
        Form.form [ onSubmit SubmitForm ]
            [ 
               Form.group (groupOption "username" model.errros)
                [ Form.label [ for "username" ] [ text "Username or Email" ]
                , Input.text
                    [ Input.id "username"
                    , Input.onInput SetUsername
                    ]
                ]

```

**Comment by rundis** [comment]
It's exposed on master now, but it wont help you much as the validation stuff has completely changed in the release version of Twitter Bootstrap 4 (and the change isn't an improvement imho... at least not in the short term for elm-bootstrap).
