### ISSUE TITLE
Modal isn't scrollable 

### ISSUE THREAD

**Issue by timleers** [rundis/elm-bootstrap#75]
Modal with a lot of content is not scrollable

will try to figure out why but i'm really new to elm

btw great work so far

**Comment by glasserc** [comment]
This is a CSS issue. Normal Bootstrap JS toggles a class "modal-open" on the <body> element, which changes the `overflow` behavior of both the <body> and the modal, with the effect that the modal becomes scrollable and the body stops being scrollable. However, Elm-Bootstrap does not add this class. I'm not even sure if it can modify the classes on the <body> tag because the <body> tag is outside what the Elm application renders.

**Comment by rundis** [comment]
Tricky one, it seems twitter bootstrap adds a class "modal-open" to the body element. Can't really think of a way to achieve that using pure elm (ie without using ports...)

**Comment by eideticplatform** [comment]
Any progress on this? i found this stackoverflow question with a relevant answer: https://stackoverflow.com/a/20393568

I am very new to elm though, can't this be done with the ffi if it's not doable directly?

**Comment by glasserc** [comment]
There are ways to work around this, but there's nothing I really feel comfortable describing as a solution. The ways that I know about for Elm to communicate with the JS runtime are 1. ports and 2. native code. Neither is allowed as part of a package on packages.elm-lang.org.

I worked around this in my application by defining two ports:

```elm
port modalOpen : () -> Cmd msg

port modalClose : () -> Cmd msg
```

And I listen for them in JS:

```js
  ports.modalOpen.subscribe(_ => {
    document.querySelector('body').classList.add('modal-open');
  });

  ports.modalClose.subscribe(_ => {
    document.querySelector('body').classList.remove('modal-open');
  });
```

Finally, I send messages to those ports when I'm opening or closing a modal. I have a bunch of modals, and a lot of structure to try to encapsulate their code and state, and I didn't want to break that encapsulation by trying to determine (for each modal) whether it had just opened or closed. On top of that, I was afraid that I would forget a code path and forget to close a certain modal but only sometimes. So I ended up wrapping my toplevel update function using something like this:

```elm
updateAndMaybeToggleModal : Msg -> Model -> ( Model, Cmd Msg )
updateAndMaybeToggleModal msg model =
    let
        ( newModel, cmds ) =
            update msg model

        openModals =
            -- Each modal is represented by a `Maybe SpecificModalState` in the toplevel model.
            -- It's Nothing if the modal is closed and Just modalState if it's open.
            -- Here, I use http://package.elm-lang.org/packages/elm-community/maybe-extra/4.0.0/Maybe-Extra
            -- to try to find the open modal (if any).
            MaybeExt.values
                -- The numbers here are meaningless, I just needed to have things of the same type.
                [ Maybe.map (always 1) newModel.firstModal
                , Maybe.map (always 2) newModel.secondModal
                , Maybe.map (always 3) newModel.thirdModal
                ]
    in
        ( newModel
        , Cmd.batch
            [ cmds
            , case openModals of
                [] ->
                    Ports.modalClose ()

                _ ->
                    Ports.modalOpen ()
            ]
        )
```

**Comment by eideticplatform** [comment]
Alright thank you for the workaround!

**Comment by eideticplatform** [comment]
Even though this worked, scrolling on ios devices seems to fail (the background scrolls) it seems bootstrap has fixed this issue a long time ago. Is there any other class that must be added other than modal-open? in the bootstrap docs for v4 alpha there is a modal dialog and scrolling it on ios works.

**Comment by eideticplatform** [comment]
a pointer-events:none; style is added to the div with the modal class. This doesn't exist in the default bootstrap examples. Is there any reason to add this? Because it is what disable scrolling on ios

**Comment by freiguy1** [comment]
I'm sad this is still a thing. I don't really want to do all the port workaround stuff esp when it only works on some devices. I guess I'll always be using my application in full screen so my (current) modals don't need to scroll.

**Comment by r1sc** [comment]
I worked around it by using @glasserc 's port solution + a CSS override to remove the "pointer-events: none" thing:
```
.modal {
    pointer-events: initial !important;
}
```

**Comment by rundis** [comment]
Introduced option for scrollable body. Not nearly as neat, but the best I can come up with for now.
Open to PRs if anyone comes up with something really clever...
