### ISSUE TITLE
Dropdown disable doesn't work as expected

### ISSUE THREAD

**Issue by jbaird03** [rundis/elm-bootstrap#77]
I am using the bootstrap DropDown, and I have been unable to make the dropdown itself disabled. I can place the class "disabled" in the class set for each individual item in the drop down, but i would like to be able to disable the dropdown such that a user would be unable to open up the dropdown itself. 

I would like to do something like the following for reference:

[ Dropdown.dropdown
                    model.inModel.dropdownDays
                    { toggleMsg = DropdownDaysMsg
                    , toggleButton = Dropdown.toggle [ Button.primary ] [ text (toString promotion.days) ]
                    , options = [ Dropdown.attrs [ style [ ( "color", "white" ) ] , disabled True ] ]
                    , items =
                        [ Dropdown.buttonItem [ onClick (ChangeDays 1),] [ text "1" ]
                        , Dropdown.buttonItem [ onClick (ChangeDays 2) ] [ text "2" ]
                        , Dropdown.buttonItem [ onClick (ChangeDays 3) ] [ text "3" ]
                        , Dropdown.buttonItem [ onClick (ChangeDays 4) ] [ text "4" ]
                        , Dropdown.buttonItem [ onClick (ChangeDays 5) ] [ text "5" ]
                        ]
                    }
                ]

**Comment by rundis** [comment]
Sounds like you want to disable the toggleButton.  Try adding ˋ Button.disabled Trueˋ to the options list in your call to ˋDropdown.toggleˋ
