### ISSUE TITLE
Dropdown Disabled Item still allows selection

### ISSUE THREAD

**Issue by jbaird03** [rundis/elm-bootstrap#78]
When setting one option of a dropdown to disabled I found that I was still able to select that item in the list. On hover the mouse changed to indicate it was disabled, but upon click the item was still selected.

**Comment by rundis** [comment]
For button items you need to set the class `disabled` and the attribute/property http://package.elm-lang.org/packages/elm-lang/html/2.0.0/Html-Attributes#disabled

For anchor items you need to set the class and override the click event I believe.
