### ISSUE TITLE
Using Carousel makes not (very) secure website.

### ISSUE THREAD

**Issue by ryuheechul** [rundis/elm-bootstrap#79]
First of all, thank you for this package. I'm using it very well.
There is an issue I just found out:

This line: https://github.com/rundis/elm-bootstrap/blob/b8144c836d0c8ec1afc5d0efd6e65ec7374282c3/src/Bootstrap/Carousel.elm#L495:81
loads `http://package.elm-lang.org/assets/favicon.ico` (which is not https) and that causes browsers to warn users the website is partially not secure. 
And for FYI, the https version of that URL also doesn't work.

Can we change the behavior to use more secure URLs?

**Comment by rundis** [comment]
That whole thing is a terrible hack unfortunately.  Soon the package site will be on https I believe. But still a better solution to the underlying problem the hack tries to achieve needs to be devised.

**Comment by synalysis** [comment]
https://package.elm-lang.org/assets/favicon.ico (with https) works so I suggest to switch to https.
Maybe it's a hack, however from a user's point of view I'm just grateful for Elm-Bootstrap and I like it :-)

**Comment by rundis** [comment]
Fixed in v5.0.0

**Comment by hdumazeau** [comment]
I'm using version 4.1.0
Would it be possible to fix on version 4 (elm 0.18)

Thank you
