### ISSUE TITLE
Dropdown.toggleButton w/ non-text children doesn't trigger onClick

### ISSUE THREAD

**Issue by aaronwhite** [rundis/elm-bootstrap#89]
```
toggleButton = Dropdown.toggle [ Button.light ] [
 img [ src = "someimage"] [],
 text "Hi, I'm text
]
```
Click the text will trigger the drop down, click the image will not (but it used to in the previous version)

**Comment by rundis** [comment]
Tx for the report. I wouldn't have though this has ever worked for nested elements inside a drop down toggle.
