### ISSUE TITLE
Center display:inline elements in grid

### ISSUE THREAD

**Issue by yarus23** [rundis/elm-bootstrap#92]
In col and row it could be great to use something more simplier than Row.attrs [ class "text-center"]

**Comment by rundis** [comment]
Partially addressed by this commit: https://github.com/rundis/elm-bootstrap/commit/e1187f75fb39e20b804ef0ce807ed91c68464f38

`Grid.col [Grid.textAlign Text.alignXsCenter]` . Maybe not simpler, but more type safe 😏 

Why would you need it for Rows ?

**Comment by rundis** [comment]
Closing due to no further feedback.
