### ISSUE TITLE
Add ability to close a dropdown

### ISSUE THREAD

**Issue by mcfilib** [rundis/elm-bootstrap#94]
Hey! I'm working on an admin interface for one of our internal APIs and have run into an issue where I'd like the dropdown to close if I click on one of the containing buttons. Is this something that's supposed to happen already? If not, is it something you'd consider exposing to in the public API?

Here's a quick `gif` that hopefully demonstrates what I mean.

![peek 2018-03-09 06-40](https://user-images.githubusercontent.com/802389/37296996-77e4d324-2614-11e8-8858-fa605629f358.gif)

**Comment by rundis** [comment]
Did you remember to wire up the subscription ? It´s meant to close automatically on any mouseclick anywhere once open. But it needs the subscription to be wired up from your app to work.

**Comment by mcfilib** [comment]
Oh, of course. I created the subscription function but forgot to add it to the program record. Sorry for the noise and thank-you for your reply.
